# standard jekyll configuration

name: 菜菜博士
url: http://microcai.org
description: 博士在网络的家

permalink: date
markdown: redcarpet
baseurl: /

source: .
destination: ./_site
plugins: ./_plugins

# configuration required for some pages

domain: microcai.org
title: 菜菜博士 - 博士在网络的家
author: microcai
email: microcaicai@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: microcai

disqus:
   id: drcai
